@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor Administrator as "<<actor>>\nAdministrator"
participant domacaStranAdministratorjaView as "<<boundary>>\ndomacaStranAdministratorjaView"
participant uporabnikController as "<<control>>\nuporabnikController"
participant PrijavljenObcan as "<<entity>>\nPrijavljenObcan"

Administrator --> domacaStranAdministratorjaView: //Zahtevaj prikaz seznama občanov
activate domacaStranAdministratorjaView
domacaStranAdministratorjaView --> uporabnikController: //Zahtevaj seznam vseh občanov
activate uporabnikController
uporabnikController --> PrijavljenObcan: pridobiVsePrijavljeneObcane()
activate PrijavljenObcan
PrijavljenObcan --> uporabnikController: //Seznam vseh prijavljenih občanov
uporabnikController --> domacaStranAdministratorjaView: //Seznam vseh prijavljenih občanov
domacaStranAdministratorjaView --> Administrator: //Prikaz seznama vseh prijavljenih občanov
Administrator --> domacaStranAdministratorjaView: //Izberi občana za blokiranje
domacaStranAdministratorjaView --> Administrator: //Prikaz sporočila za potrditev blokiranja
Administrator --> domacaStranAdministratorjaView: //Potrditev blokiranja
domacaStranAdministratorjaView --> uporabnikController: blokiraj()
uporabnikController --> PrijavljenObcan: blokirajObcana()
deactivate PrijavljenObcan
uporabnikController --> domacaStranAdministratorjaView: //Sporočilo o uspešnem blokiranju
deactivate uporabnikController
domacaStranAdministratorjaView --> Administrator: //Sporočilo o uspešnem blokiranju
deactivate domacaStranAdministratorjaView
@enduml